### ISSUE TITLE
Audio Issues

### ISSUE THREAD

**Issue by Mandeepdev23** [FalconRealityDev/Falcon-CareUpGame#4]
While testing the app, I noticed there’s no audio during the patient greeting in the Catheterization protocol for changing a suprapubic catheter. This happens in both Dutch and English versions of the simulation. 

<img width="1212" alt="image 1930@2x" src="https://github.com/user-attachments/assets/77848467-0f5f-4332-a5e1-a07fcb27e7e1">

**Comment by karna1810** [comment]
Audios are played in Dutch in AED
