### ISSUE TITLE
Text Based Issues

### ISSUE THREAD

**Issue by Mandeepdev23** [FalconRealityDev/Falcon-CareUpGame#5]
Text Based Translation Issues

**Comment by Mandeepdev23** [comment]
Inject protocol - Injecting Subcutaneously with insulin pen - spelling error in "Did you know - Suitable injection areas" where **[1]**  is added after the sentence

![{2C807394-0C9F-4EB4-B21D-7A01FC0CCB0B}](https://github.com/user-attachments/assets/1f23db78-246e-489b-8b10-372310b25a3d)

**Comment by Mandeepdev23** [comment]
inject - Injecting subcutaneously with insulin pen- DUTCH 
i assume Client in DUTCH is spelled **"cliënt"** which in tag it isn't spelling that.

![{AFCD38D0-DBB6-48EC-9E1D-F471EDEA7011}](https://github.com/user-attachments/assets/445feb5e-9092-4b7f-a8d7-724cf066c1f7)

**Comment by Mandeepdev23** [comment]
Inject Protocol - Preparing medicine to inject ampoule - DUTCH
found few medical equipment which is not translated in English  
![{E61D3519-47FB-4F0C-964D-CFF8794012DC}](https://github.com/user-attachments/assets/f4a6b8b4-63cc-4077-9584-a97268dbff7e)
![{67E624B2-735F-4A9D-BBDE-405C415C816D}](https://github.com/user-attachments/assets/64e2aa08-3a63-49c4-bdcd-7a49d6626506)
![{3C746643-CD84-4925-B4CF-8CD48CD200A5}](https://github.com/user-attachments/assets/3e78a32c-cd3d-4b2a-b0fa-bc24af67070a)
![{16A0DE91-B8BC-41D4-A486-82F785D6A629}](https://github.com/user-attachments/assets/d9e27c15-545e-4231-aa53-986ff65fd126)
![{F95112FD-B5AB-4851-BA9A-25818D1B567E}](https://github.com/user-attachments/assets/1d992a3b-77d6-4e7e-bf7e-d5fd2b4da2b3)
![{5223D0B8-4489-4ACA-AE0F-FB7695D8A541}](https://github.com/user-attachments/assets/a1cb6fd4-0e8b-461f-9502-18685028bee3)
![{99F2931B-9442-4AF4-ADDB-889835DED882}](https://github.com/user-attachments/assets/7691dd01-70e1-4792-bd1d-b310ae074ca0)
![{20C154A3-34C0-4BBA-83B3-C55ADC2310ED}](https://github.com/user-attachments/assets/1286d277-0ff1-43c9-a989-f528d7618e60)

**Comment by Mandeepdev23** [comment]
Inject Protocol - Preparing medicine to inject ampoule - DUTCH
Very good dialog box after opening syringe with suction needle and MCQ questions 
![{C37AC076-329C-4C99-94C9-D31C8473197E}](https://github.com/user-attachments/assets/163ff4f6-6bbd-412e-bc67-339218bc9bc8)

**Comment by Mandeepdev23** [comment]
Inject Protocol - Preparing medicine to inject vial - ENGLISH
the top suggestions "what are you going to do"
**- Take.**  
i'm not sure if theres something to be added or not. 
![{34D291B2-9495-49C5-AB69-645C29EA9109}](https://github.com/user-attachments/assets/929aa022-298a-4ad9-aa80-b318993cf706)

**Comment by Mandeepdev23** [comment]
Inject Protocol - Preparing medicine to inject vial - ENGLISH
 A missing MCQ answers after asking with the assistance nurse for her double checking routine 
![{78860F16-5053-4928-AFF6-06FDD68C25B7}](https://github.com/user-attachments/assets/3a51acf5-4909-4bce-977c-56d20ef972f5)

**Comment by Mandeepdev23** [comment]
Inject Protocol - Preparing medicine to inject vial - ENGLISH/DUTCH
a Glitch in Ui exactly same in Dutch and English after the **tapping the syringe** in the end of the simulation 

![{C78FB219-FEA0-4146-ADAD-631864551C64}](https://github.com/user-attachments/assets/25bc3d27-e304-4d78-a4d4-8ee09129a5c8)

**Comment by Mandeepdev23** [comment]
Inject Protocol - Preparing medicine to inject solution - ENGLISH/DUTCH
Same simultion UI glitch
![{2B6440C4-7A26-4946-A523-D84E85E20812}](https://github.com/user-attachments/assets/581721d0-a386-4131-8c55-4d5b2f6b03fe)

**Comment by Mandeepdev23** [comment]
Inject Protocol - Subcutaneous injection (skin fold) - ENGLISH
While testing the Injection simulation, I noticed a spelling mistake in the English language version of the protocol. The text reads: "check client name and date of birthh" with an extra "h" at the end.

![{9857EF89-ADCF-4AE8-BC78-718847F2B3E0}](https://github.com/user-attachments/assets/8d2420b2-c86a-4f79-bd36-da6071999149)

**Comment by Mandeepdev23** [comment]
Inject Protocol - Subcutaneous injection (perpendicular tech. ) - ENGLISH
An miss alignment ?? on **" Method of administration and Time of day "**

![{87EB8624-7E6B-4FFD-9B5B-0D1C35083D54}](https://github.com/user-attachments/assets/3583fde4-349b-46f1-a91e-5a23a4069d7c)

**Comment by Mandeepdev23** [comment]
Inject Protocol - Subcutaneous injection (perpendicular tech. ) - ENGLISH
While testing the Injection simulation, I noticed a spelling mistake in the English language version of the protocol. The text reads: "check client name and date of birthh" with an extra "h" at the end.
![{643AC2D9-CCCD-4268-A33C-04AEC7250A71}](https://github.com/user-attachments/assets/2608432d-1006-4267-ab26-6666853df6d7)

**Comment by Mandeepdev23** [comment]
Inject Protocol - Subcutaneous injection (perpendicular tech. ) - ENGLISH
Maybe Expiry date **" : "**
![{61D512EE-4CCF-4617-A087-C93C7F4B2306}](https://github.com/user-attachments/assets/b32431a2-fed8-4e7f-bf7c-46e4761ad469)

**Comment by Mandeepdev23** [comment]
Inject Protocol - Subcutaneous injection (perpendicular tech. ) - ENGLISH
Again the Ui glitch the tapping the syringe  
![{34A0C4B2-1879-4292-A1B5-9D7BA2D3DE78}](https://github.com/user-attachments/assets/61848d8f-a30e-428b-91cd-888f1d965c80)

**Comment by Mandeepdev23** [comment]
Administer medication - Administer medications into cheek pouch - DUTCH

I Don't know if its correct but in the MCQ on of the answers where given as **Client333**  
unfortunately the unity crashed and computer shutdown, and the recording wasn't saved.

i tried going through the simulation again, but couldn't find that same MCQ

**Comment by karna1810** [comment]
In the Main Menu the text inside the thumbnail of Free is in Dutch

![image](https://github.com/user-attachments/assets/f10c8626-6c3f-4dbc-8bb6-4e710d038cb5)

**Comment by Mandeepdev23** [comment]
Administer medication - oxygen via oxygen cannula -ENGLISH
"Client" in Dutch, where as it should be in ENGLISH
![{694D413B-A7EF-4DB9-9F6A-AFA155116405}](https://github.com/user-attachments/assets/683f3f6d-0370-4dcf-83ef-6bb583b801e3)

**Comment by Mandeepdev23** [comment]
Administer medication - oxygen via oxygen cannula -ENGLISH

 medical equipment is translated in **dutch** scene when connecting to oxygen 

![{1E4DECBA-55D3-488D-95DD-9742F19FFA83}](https://github.com/user-attachments/assets/6d07dbd0-c188-416f-916e-d433cd0fa932)

**Comment by Mandeepdev23** [comment]
Administer medication - oxygen via oxygen cannula -DUTCH

Translation error maybe ? 

![{1A9AF161-7BD3-419A-8EBB-AEFDF3F7123B}](https://github.com/user-attachments/assets/dd67fc66-94b3-43fe-88a9-c087840251aa)

**Comment by Mandeepdev23** [comment]
ostomy care - skin barrier as one piece system - ENGLISH

**Toilet paper** spelling mistake  
![{3C62A813-046F-4361-9ABC-A73A4E608E56}](https://github.com/user-attachments/assets/4c412a9a-89ce-4a45-8757-97186ef26ac6)

**Comment by Mandeepdev23** [comment]
ostomy care - skin barrier as two piece system - ENGLISH

I am not sure if it was supposed to be **NB**  if soo, then no issue here

![{A135ECFC-186B-4139-85CA-8467B89BCB27}](https://github.com/user-attachments/assets/7ec85a93-dc41-48b2-8117-3424fbe0d594)

**Comment by Mandeepdev23** [comment]
tube feeding - Administer nutrution via nosogastric-DUTCH
I Think **"Pack"** from medical equipment should have been translated in DUTCH!
[{D64DB4F7-744B-451C-8AF5-F6AB82A0A8F2}](https://github.com/user-attachments/assets/0436a971-6b97-4393-98d3-911626ef2d64)

**Comment by Mandeepdev23** [comment]
Wound care - DUTCH
i feel like scissor and Tweezers are not translated 

![{6F4CDFE8-87F7-4D50-9B5C-F2304A0A79B0}](https://github.com/user-attachments/assets/3c084074-fb78-4255-ab12-662b8d95c1c9)
![{A18EB115-4F58-43E9-877F-F93D98109629}](https://github.com/user-attachments/assets/0a4eabae-d78f-45e3-9dcb-72bc2d9b47b1)

**Comment by Mandeepdev23** [comment]
Wound care - DUTCH/ENGLISH 

i feel like this is fixed, if not here you go **Pak.**  the missing sentence 
  
![{FB8049F4-7F4B-4EC5-B813-9DECEF1DB240}](https://github.com/user-attachments/assets/71f731b3-36a6-4c2d-86c8-fb1c58f169cd)

**Comment by Mandeepdev23** [comment]
Emergency response - ENGLISH
Missing text !!!!!

![{77F4B2D8-7456-4E72-9D08-30309BC17605}](https://github.com/user-attachments/assets/24b10298-d0be-4bab-bde6-90241b203af6)

**Comment by Mandeepdev23** [comment]
Bandaging - ENGLISH/DUTCH

Equipment naming missing 

![{518DA919-133B-4688-9A38-B0257A5BEDA7}](https://github.com/user-attachments/assets/6577c9d8-cd7f-46ae-8a2b-3e28361982cb)
![{5CC51E8D-88DD-4593-B9BD-1C868826B8C4}](https://github.com/user-attachments/assets/2a6ff3b6-9d2f-442a-a252-ba5e844986fd)
![{A93BA441-DBEC-4EB2-9E55-E41D024D739D}](https://github.com/user-attachments/assets/d9aba770-cf6c-45e5-aa73-ba5868f1a421)

**Comment by Mandeepdev23** [comment]
Catherterization - Bladder catherterization in a man - ENGLISH/DUTCH

Take. and then rest of the sentence is missing
![{81D264E8-5AB3-401B-A879-91E5F9344DA2}](https://github.com/user-attachments/assets/9b77c2eb-4b27-43c7-a811-306cf30c9b0c)

/r/ needs to be removed
![Uploading {DE5EFD3A-18C3-4B1B-91E3-B3D0311C882C}.png…]()

**Comment by karna1810** [comment]
Hint not displayed for Oxygen Cannula in Scenes_OxygenThroughCannula

![image](https://github.com/user-attachments/assets/b6b6137a-2d3c-4c8f-b4b0-18187400affa)

**Comment by Mandeepdev23** [comment]
Inject - Subcutaneously with insulin pen - ENGLISH

[1] 

![{96489BB0-4725-4348-87E8-5402A85E162E}](https://github.com/user-attachments/assets/d81d41ce-ccf7-453d-b673-3dbec05d8feb)

**Comment by Mandeepdev23** [comment]
Inject - Subcutaneous injection (skin fold) - ENGLISH

Birthh still isn't fixed
![{C28DB70D-4AA7-4409-AB62-6BCA1A7E19DB}](https://github.com/user-attachments/assets/f6766786-3718-4460-93b1-35c41cd04345)

translation error on the syringe bit
![{4A6945D0-441D-4CB6-9F95-31ABE3BBD805}](https://github.com/user-attachments/assets/666db531-c316-4e83-9338-7d3683177c71)

![{BB154A74-1A4B-4D86-8400-B26F9FAE815D}](https://github.com/user-attachments/assets/adc52435-1173-49e9-998c-011ea98d2f9c)

![{D48776CA-7DC9-483C-B4A9-C71412B02635}](https://github.com/user-attachments/assets/4a8c3073-fcc0-4aae-917a-40bdbd3eef78)

**Comment by Mandeepdev23** [comment]
Inject - Subcutaneous injection (skin fold) - DUTCH

Client in Dutch is not translated 

![{5C2F51ED-8758-463E-92F4-AC5E56882B06}](https://github.com/user-attachments/assets/e9307e5f-fcae-4da9-9d07-f57fa15f44dc)

**Comment by Mandeepdev23** [comment]
Inject - Preparing medicine to inject ampoule - ENGLISH

I don't know if its called Light blub, the dutch translation says **ampul**

![{773C648F-4A80-47C8-9ACC-A803F2917333}](https://github.com/user-attachments/assets/923500e4-0f54-48a2-ba60-210c45d5c1fd)

**Comment by Mandeepdev23** [comment]
Administer medication - via subcutaneous cannula bolus - ENGLISH

**Luerlock** or **Lure lock** 

![{4AB7986F-4429-4C1C-9034-681903285632}](https://github.com/user-attachments/assets/fc5d7ea7-6731-4d23-82cd-56c14ddf1bc4)

**Comment by Mandeepdev23** [comment]
Administer medication - via subcutaneous cannula bolus - ENGLISH

**No touch-method,**  does method have E in the end? 
![{DD64D947-EC74-4E3F-8D8A-7B775666A7DF}](https://github.com/user-attachments/assets/c01a6fa8-ed1f-4419-9794-e7e53aa3a8c0)

**Comment by Mandeepdev23** [comment]
Administer medication -oxygen via oxygen cannula - ENGLISH

**Client** which needs to be in English

![{B41F97DE-AFE5-41DF-987F-C145A4797A0B}](https://github.com/user-attachments/assets/fc7f7cfb-6328-48e6-99e3-79f9e9042809)

**Comment by Mandeepdev23** [comment]
Administer medication - under the tongue - DUTCH

**Spray of tablet** should be translated it in **DUTCH** 

![{91440C15-916E-4039-8384-C2E8C9259541}](https://github.com/user-attachments/assets/eae19caf-40de-477c-93a2-e97b60dba2ba)

**Comment by Mandeepdev23** [comment]
Subcutaneous infusion cannula - Inserting the Saf - Intima  - ENGLISH

unclamp cannulas, not sure if it's the correct sentence 

![{EF5EF1AC-7598-4AB1-A0FC-E62A990C3789}](https://github.com/user-attachments/assets/19ad15b8-91f9-4811-81ee-0d0526b58829)

**Comment by Mandeepdev23** [comment]
Subcutaneous infusion cannula - Inserting peripheral infusion - DUTCH/ENGLISH

**Black info screen,** 

![{11980270-2879-4F9E-9C45-9B69C92AE409}](https://github.com/user-attachments/assets/18e4c564-e500-4bb4-b2bf-53e6a7e25770)

**Comment by Mandeepdev23** [comment]
Subcutaneous infusion cannula - Inserting the Saf - Intima  - DUTCH

Disinfectants needs to be translated in Dutch 

![{0DBA2273-CABE-4E3A-AD4C-6AFAA398AD88}](https://github.com/user-attachments/assets/a580aec7-87f4-4404-b590-76c167dda4e0)

**Comment by Mandeepdev23** [comment]
Tube feeding - administer nutrition via nasogastric tube ENGLISH

**PACK PACK!!!**
![{7A2FBBEC-CAA8-4389-BD3B-4439FAC073C9}](https://github.com/user-attachments/assets/82387a1e-7841-47ee-8dcf-c87e5c44af9f)

**Comment by Mandeepdev23** [comment]
Tube feeding - administer nutrition via nasogastric tube DUTCH

**Pak pak pak**
![{66C8CF7E-3406-4348-B7E2-D9F9B638D302}](https://github.com/user-attachments/assets/65306ba6-8e72-4946-ac99-974f34444d69)

**Comment by karna1810** [comment]
Comes in the build when hosted in test server
![image](https://github.com/user-attachments/assets/02b146ed-99b9-48f2-b743-8c5a4003a44a)
