### ISSUE TITLE
Blank Option in MCQ Quiz 

### ISSUE THREAD

**Issue by karna1810** [FalconRealityDev/Falcon-CareUpGame#6]
This happens in multiple scenes. A few are listed below

The below one is from **Preparing medicine to inject vial** 
![image](https://github.com/user-attachments/assets/130b7fab-f214-4a7c-924e-aa197f0bfc8c)

The below one is from **Preparing medicine to inject solution**
![image](https://github.com/user-attachments/assets/223b2232-b772-49da-bbd1-b72d082cd9a5)

**Comment by Mandeepdev23** [comment]
Missing something here?? i assume 

![{5D58EBDA-9A7F-411E-A275-0411DFD0908A}](https://github.com/user-attachments/assets/645d9c1a-982e-468d-8abd-b9a1e83fb409)

**Comment by Mandeepdev23** [comment]
Administer medication - oxygen via oxygen cannula -ENGLISH

i hope this was fixed in the last issue 

![{28CC2F48-BC8A-4C3F-9256-F7054A01C370}](https://github.com/user-attachments/assets/7f00ee41-3beb-4709-b013-d7243d0bdc91)

**Comment by Mandeepdev23** [comment]
ostomy care - skin barrier as two piece system - ENGLISH

Missing MCQ 

![{8FB35B14-3E79-439F-B056-DBFFFB90E0B3}](https://github.com/user-attachments/assets/662c1187-98dc-4fb0-b0f9-fd5b26e8169f)

**Comment by karna1810** [comment]
Blank Options were shown because a the dictionary for random events was not created for english words
